@host = https://localhost:7164

Post {{host}}/Authentication/Register
Content-Type: application/json

{   
    "firstName": "Tiffany",
    "lastName": "Doe",
    "email": "user@gmail.com",
    "password": "1234567"   
}
